# Librerías

In [1]:
#Importamos las librerías estándar
%matplotlib inline
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from google.colab import drive
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix

In [2]:
#Importamos las librerías de Keras
from keras.models import Sequential
from keras.layers import Dense
from tensorflow.keras.optimizers import SGD, Adam

# Conexión al repositorio de datos

In [3]:
#Accedemos a Google Drive
drive.mount('/content/drive')

Mounted at /content/drive


# Lectura de datos

In [5]:
#Trabajaremos con un dataset que clasifica flores según sus características
#Tiene los siguientes campos:
# - sepal_length: Longitud del sépalo
# - sepal_width: Ancho del sépalo
# - petal_length: Longitud del pétalo
# - petal_width: Ancho del pétalo
# - species: Tipo de flor de iris (setosa, versicolor, virginica)
df = pd.read_csv('/content/drive/MyDrive/Data/iris.csv')
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [6]:
#Vemos las tres clasificaciones que existen
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

# Selección de features

In [7]:
x = df[['sepal_length', 'sepal_width', 'petal_length', 'petal_width']].values
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

# Selección de labels

In [8]:
#El label "species" que queremos predecir, tiene data categórica
y = df['species'].values
y

array(['setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolo

In [12]:
#Primero tenemos que darle una representación numérica a cada dato
representacion = {
    'setosa' : 0,
    'versicolor' : 1,
    'virginica' : 2,
}

representacion

{'setosa': 0, 'versicolor': 1, 'virginica': 2}

In [13]:
#Luego mapeamos los valores de "Y" por su representación numérica
y_numerico = df['species'].map(representacion)
y_numerico

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: species, Length: 150, dtype: int64

In [14]:
#Tenemos que darle una estructura de campos dummies
#Usaremos una librería de Keras
from keras.utils.np_utils import to_categorical

In [15]:
#Creamos tres columnas de salidas
y_categorico = to_categorical(y_numerico)
y_categorico

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

# Datos de entrenamiento y validación

In [16]:
#Segmentamos la data
x_train, x_test, y_train, y_test = train_test_split(x, y_categorico, test_size=0.2)

In [ ]:
#Features de entrenamiento
x_train

array([[5.6, 3. , 4.1, 1.3],
       [6.6, 2.9, 4.6, 1.3],
       [6.3, 3.3, 6. , 2.5],
       [5.8, 2.7, 4.1, 1. ],
       [7.7, 3.8, 6.7, 2.2],
       [5.6, 2.5, 3.9, 1.1],
       [5.7, 2.8, 4.1, 1.3],
       [5. , 3.5, 1.3, 0.3],
       [6. , 2.2, 5. , 1.5],
       [5.8, 4. , 1.2, 0.2],
       [4.9, 3.1, 1.5, 0.2],
       [6.1, 2.8, 4.7, 1.2],
       [6. , 2.7, 5.1, 1.6],
       [4.7, 3.2, 1.6, 0.2],
       [6.3, 3.3, 4.7, 1.6],
       [4.9, 2.5, 4.5, 1.7],
       [4.8, 3.1, 1.6, 0.2],
       [4.6, 3.6, 1. , 0.2],
       [4.8, 3. , 1.4, 0.3],
       [6.2, 3.4, 5.4, 2.3],
       [6.7, 3.3, 5.7, 2.1],
       [6.8, 3. , 5.5, 2.1],
       [5.9, 3. , 5.1, 1.8],
       [5.7, 2.9, 4.2, 1.3],
       [5.1, 3.3, 1.7, 0.5],
       [5. , 3.5, 1.6, 0.6],
       [7.6, 3. , 6.6, 2.1],
       [4.9, 3.6, 1.4, 0.1],
       [7.9, 3.8, 6.4, 2. ],
       [5. , 3.2, 1.2, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [4.3, 3. , 1.1, 0.1],
       [7.7, 3. , 6.1, 2.3],
       [5.1, 3.8, 1.5, 0.3],
       [5. , 3

In [17]:
#Features de test
x_test

array([[6. , 3. , 4.8, 1.8],
       [4.6, 3.4, 1.4, 0.3],
       [6.3, 2.7, 4.9, 1.8],
       [5.6, 2.9, 3.6, 1.3],
       [5.2, 2.7, 3.9, 1.4],
       [6.4, 2.8, 5.6, 2.2],
       [7.6, 3. , 6.6, 2.1],
       [5.7, 4.4, 1.5, 0.4],
       [7.7, 3.8, 6.7, 2.2],
       [7.7, 3. , 6.1, 2.3],
       [5.8, 2.7, 3.9, 1.2],
       [6.7, 3.3, 5.7, 2.1],
       [4.5, 2.3, 1.3, 0.3],
       [7.7, 2.8, 6.7, 2. ],
       [4.6, 3.1, 1.5, 0.2],
       [7.2, 3. , 5.8, 1.6],
       [5.2, 4.1, 1.5, 0.1],
       [4.7, 3.2, 1.6, 0.2],
       [6.7, 3. , 5. , 1.7],
       [4.9, 3.1, 1.5, 0.1],
       [6.7, 2.5, 5.8, 1.8],
       [7.9, 3.8, 6.4, 2. ],
       [6.3, 2.5, 4.9, 1.5],
       [6. , 2.9, 4.5, 1.5],
       [7.4, 2.8, 6.1, 1.9],
       [5.4, 3.9, 1.3, 0.4],
       [5. , 3.2, 1.2, 0.2],
       [5.8, 2.7, 5.1, 1.9],
       [5.7, 2.8, 4.1, 1.3],
       [7.1, 3. , 5.9, 2.1]])

In [18]:
#Labels de entrenamiento
y_train

array([[1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0

In [19]:
#Labels de test
y_test

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)

# Configuración de la red neuronal

In [20]:
#Instaciamos un modelo
model = Sequential()

In [21]:
#Agregamos una capa de:
# - 3 neuronas
# - 4 inputs (sepal_length, sepal_width, petal_length, petal_width)
# - Como estamos frente a un problema de clasificación multi-clase, la F.A. más adecuada es la "softmax"
model.add(Dense(3, input_shape=(4,), activation='softmax'))

In [25]:
#Compilamos el modelo
#Utilizamos la función "categorical_crossentropy" como medida del error
model.compile(Adam(learning_rate=0.1), loss='categorical_crossentropy', metrics=['accuracy'])

# Entrenamiento del modelo

In [26]:
#Entrenamos el modelo
model.fit(x_train, y_train, epochs=20, validation_split=0.1)

Epoch 1/20
4/4 [==============================] - 1s 50ms/step - loss: 2.3426 - accuracy: 0.2222 - val_loss: 1.9305 - val_accuracy: 0.2500
Epoch 2/20
4/4 [==============================] - 0s 7ms/step - loss: 1.4341 - accuracy: 0.3519 - val_loss: 0.9589 - val_accuracy: 0.7500
Epoch 3/20
4/4 [==============================] - 0s 8ms/step - loss: 1.0037 - accuracy: 0.6944 - val_loss: 0.6850 - val_accuracy: 0.7500
Epoch 4/20
4/4 [==============================] - 0s 8ms/step - loss: 0.6568 - accuracy: 0.7037 - val_loss: 0.6129 - val_accuracy: 0.6667
Epoch 5/20
4/4 [==============================] - 0s 6ms/step - loss: 0.5863 - accuracy: 0.6481 - val_loss: 0.4435 - val_accuracy: 0.8333
Epoch 6/20
4/4 [==============================] - 0s 7ms/step - loss: 0.4500 - accuracy: 0.8519 - val_loss: 0.4015 - val_accuracy: 0.7500
Epoch 7/20
4/4 [==============================] - 0s 7ms/step - loss: 0.4109 - accuracy: 0.8426 - val_loss: 0.3843 - val_accuracy: 0.8333
Epoch 8/20
4/4 [=================

# Validación del modelo

In [27]:
#Utilizamos los datos de testing para ver el porcentaje de aciertos que tiene el modelo
y_prediccion = model.predict(x_test)

#Vemos las probabilidades de cada categoría
#La probabilidad que tenga mayor valor determina la categoría a la que pertence el registro que se evalua
y_prediccion.round(3)

array([[0.002, 0.429, 0.568],
       [0.966, 0.033, 0.   ],
       [0.001, 0.475, 0.524],
       [0.061, 0.776, 0.163],
       [0.018, 0.626, 0.355],
       [0.   , 0.168, 0.832],
       [0.   , 0.317, 0.683],
       [0.99 , 0.01 , 0.   ],
       [0.   , 0.304, 0.696],
       [0.   , 0.311, 0.689],
       [0.031, 0.828, 0.142],
       [0.   , 0.275, 0.725],
       [0.868, 0.131, 0.001],
       [0.   , 0.374, 0.626],
       [0.944, 0.056, 0.   ],
       [0.001, 0.684, 0.315],
       [0.989, 0.011, 0.   ],
       [0.942, 0.057, 0.   ],
       [0.003, 0.643, 0.354],
       [0.95 , 0.05 , 0.   ],
       [0.   , 0.395, 0.605],
       [0.   , 0.542, 0.457],
       [0.002, 0.659, 0.339],
       [0.008, 0.672, 0.32 ],
       [0.   , 0.476, 0.524],
       [0.986, 0.014, 0.   ],
       [0.972, 0.027, 0.   ],
       [0.   , 0.254, 0.746],
       [0.02 , 0.761, 0.218],
       [0.   , 0.319, 0.681]], dtype=float32)

In [32]:
#Las probabilidades de cada categoría se mostrarán en el orden que definimos en esta variable
representacion

{'setosa': 0, 'versicolor': 1, 'virginica': 2}

In [33]:
#Vamos a obtener el índice del valor máximo de cada predicción para saber a qué categoría pertenece
y_prediccion_categorico = np.argmax(y_prediccion, axis = 1)
y_prediccion_categorico

array([2, 0, 2, 1, 1, 2, 2, 0, 2, 2, 1, 2, 0, 2, 0, 1, 0, 0, 1, 0, 2, 1,
       1, 1, 2, 0, 0, 2, 1, 2])

# Evaluación del modelo

In [34]:
#Estos son los Y reales para testing
#También lo tenemos que categorizar
y_test

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)

In [35]:
#Categorizamos la data de test
y_test_categorico = np.argmax(y_test, axis = 1)
y_test_categorico

array([2, 0, 2, 1, 1, 2, 2, 0, 2, 2, 1, 2, 0, 2, 0, 2, 0, 0, 1, 0, 2, 2,
       1, 1, 2, 0, 0, 2, 1, 2])

In [36]:
#Imprimimos la matriz de confusión
confusion_matrix(y_test_categorico, y_prediccion_categorico)

array([[ 9,  0,  0],
       [ 0,  7,  0],
       [ 0,  2, 12]])

In [37]:
#Crearemos una función utilitaria para pintar la matriz de mejor manera
def pintar_matriz_de_confusion(y, y_prediccion_binaria, etiquetas):
    #Obtenemos la matriz de confusion
    matriz_de_confusion = confusion_matrix(y, y_prediccion_binaria)

    #Agregamos el prefijo "PREDICCION " a las etiquetas
    etiquetas_prediccion = ['PREDICCION '+ l for l in etiquetas]

    #Creamos un dataframe pandas
    df = pd.DataFrame(matriz_de_confusion, index=etiquetas, columns=etiquetas_prediccion)

    return df

In [ ]:
#Imprimos la matriz de confusión
pintar_matriz_de_confusion(y_test_categorico, y_prediccion_categorico, ['setosa', 'versicolor', 'virginica'])

PREDICCION setosa  PREDICCION versicolor  PREDICCION virginica
setosa                      6                      0                     0
versicolor                  0                     15                     0
virginica                   0                      0                     9